/* Events */
export const SET_EVENTS = "GET_EVENTS"
export const EDIT_EVENT = "EDIT_EVENT"
export const EDIT_EVENT_ERROR = "EDIT_EVENT_ERROR"
export const CREATE_PUBLIC_EVENT = "CREATE_PUBLIC_EVENT"
export const CREATE_PRIVATE_EVENT = "CREATE_PRIVATE_EVENT"
export const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR"

/* Users */
export const LOG_IN_USER = "LOG_IN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"


export const CLEAR_ERROR = "CLEAR_ERROR"

